import type { Metadata } from "next"
import localFont from "next/font/local"

import "./globals.css"
import { GoogleTagManager } from "@next/third-parties/google"

import Header from "./components/header"

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
})
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  openGraph: {
    title: "Test Site",
    description: "Test site description",
    url: "https://example.com",
    siteName: "Test Site",
  },
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const gtmId: string = process.env.NEXT_PUBLIC_GTM_ID || ""

  return (
    <html lang="en">
      <GoogleTagManager gtmId={gtmId} />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />

        {children}
      </body>
    </html>
  )
}
