import { Metadata } from "next"

import Contents from "./components/contents"

export const metadata: Metadata = {
  title: "shadcn - Test Site",
  description: "Generated by create next app",
  openGraph: {
    title: "shadcn - Test Site",
    description: "shadcn page description",
    url: "https://example.com",
    siteName: "shadcn - Test Site",
  },
}

export default function ShadcnPage() {
  return <Contents />
}
